openapi: 3.0.0
info:
  title: device-management
  version: 1.0.0

paths:
  /devices:
    post:
      summary: Создать устройство
      description: Создание нового устройства
      x-kusk:
        upstream:
          service:
            name: device-management
            namespace: default
            port: 8080
      responses:
        '201':
          description: Устройство успешно создано
        '400':
          description: Неверные данные
        '500':
          description: Ошибка сервера

  /devices/{id}:
    get:
      summary: Получить информацию об устройстве
      x-kusk:
        upstream:
          service:
            name: device-management
            namespace: default
            port: 8080
      responses:
        '200':
          description: Информация об устройстве
        '404':
          description: Устройство не найдено
        '500':
          description: Ошибка сервера

    put:
      summary: Изменить состояние устройства
      x-kusk:
        upstream:
          service:
            name: device-management
            namespace: default
            port: 8080
      responses:
        '200':
          description: Состояние устройства успешно обновлено
        '404':
          description: Устройство не найдено
        '500':
          description: Ошибка сервера

  /devices/{id}/connect:
    post:
      summary: Подключить устройство
      x-kusk:
        upstream:
          service:
            name: device-management
            namespace: default
            port: 8080
      responses:
        '200':
          description: Устройство успешно подключено
        '404':
          description: Устройство не найдено
        '500':
          description: Ошибка сервера

  /devices/{id}/disconnect:
    post:
      summary: Отключить устройство
      x-kusk:
        upstream:
          service:
            name: device-management
            namespace: default
            port: 8080
      responses:
        '200':
          description: Устройство успешно отключено
        '404':
          description: Устройство не найдено
        '500':
          description: Ошибка сервера

  /devices/{id}/scenario:
    post:
      summary: Задать сценарий для устройства
      x-kusk:
        upstream:
          service:
            name: device-management
            namespace: default
            port: 8080
      responses:
        '200':
          description: Сценарий успешно задан
        '404':
          description: Устройство не найдено
        '500':
          description: Ошибка сервера