apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-telemetry
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-telemetry
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-telemetry
    spec:
      containers:
        - name: telemetry
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8081
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: {{ .Values.kafka.bootstrapServers }}
