apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-telemetry
spec:
  selector:
    app: {{ .Release.Name }}-telemetry
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8081
