@startuml
title Device Management Component Diagram

top to bottom direction

!include C4_Component.puml

Container_Boundary(SmartHomeSystem, "Система умного дома") {
  Container(DeviceManagement, "Device Management", "Java, Spring Boot", "Управляет подключением и отключением устройств, автоматизацией сценариев")
}

Container(DeviceManagement, "Device Management", "Java, Spring Boot") {
  Component(DeviceController, "Device Controller", "Обрабатывает запросы от устройства")
  Component(EventManager, "Event Manager", "Публикует сообщения в очередь")
  Component(DeviceRegistry, "Device Registry", "Хранит информацию о подключенных устройствах")
}
@enduml