@startuml
title Kafka Component Diagram

top to bottom direction

!include C4_Component.puml

Container_Boundary(SmartHomeSystem, "Система умного дома") {
  Container(Kafka, "Kafka", "Apache Kafka", "Брокер сообщений для асинхронного взаимодействия между микросервисами")
}

Container(Kafka, "Kafka", "Apache Kafka") {
  Component(Producer, "Producer", "Отправляет сообщения в топики Kafka")
  Component(Broker, "Broker", "Принимает, хранит и доставляет сообщения")
  Component(Consumer, "Consumer", "Читает сообщения из топиков Kafka")
  Component(Zookeeper, "Zookeeper", "Управляет координацией брокеров в кластере Kafka")
}

Rel(Producer, Broker, "Отправляет сообщения в топики через")
Rel(Broker, Consumer, "Доставляет сообщения потребителям через")
Rel(Zookeeper, Broker, "Координирует работу брокеров в кластере")
@enduml